title: "Thalman Thilak - Blog"
description: "Product Manager, Rollout Specialist, AI Enthusiast"
author: "Thalman Thilak"
baseurl: "/blog"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

paginate: 5
