title: Thalman Thilak Blog
description: My thoughts on various topics
url: "https://blog.thalmanthilak.com"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Excerpt settings
excerpt_separator: <!--more-->

# Permalink structure
permalink: /:year/:month/:day/:title/
