title: Thalman Thilak Blog
description: My thoughts on various topics
url: "https://thalmanthilak.github.io"
baseurl: "/blog"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Excerpt settings
excerpt_separator: <!--more-->

# Permalink structure
permalink: /:year/:month/:day/:title/
