title: "Thalman Thilak - Blog"
description: "Product Manager, Rollout Specialist, AI Enthusiast"
author: "Thalman Thilak"
baseurl: "/blog"

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-sitemap

paginate: 5
