title: "Thalman Thilak - Blog"
description: "Product Manager, Rollout Specialist, AI Enthusiast"
author: "Thalman Thilak"
baseurl: "/blog"

markdown: kramdown
theme: jekyll-theme-cayman       # Modern, colorful
theme: jekyll-theme-architect    # Professional
theme: jekyll-theme-midnight     # Dark theme
remote_theme: mmistakes/minimal-mistakes  # Very popular, highly customizable
plugins:
  - jekyll-feed
  - jekyll-sitemap

paginate: 5
